onerror {resume}
add list -width 18 /top_tb/done_FSM
add list /top_tb/rst
add list /top_tb/ena
add list /top_tb/clk
add list /top_tb/TBactive
add list /top_tb/TBWriteEnableDataMem
add list /top_tb/TBWriteEnableProgMem
add list /top_tb/TBdataInDataMem
add list /top_tb/TBdataOutDataMem
add list /top_tb/TBdataInProgMem
add list /top_tb/TBWriteAddressDataMem
add list /top_tb/TBWriteAddressProgMem
add list /top_tb/TBReadAddressDataMem
add list /top_tb/donePmemIn
add list /top_tb/doneDmemIn
add list /top_tb/TopUnit/ControlUnit/st
add list /top_tb/TopUnit/ControlUnit/ld
add list /top_tb/TopUnit/ControlUnit/mov
add list /top_tb/TopUnit/ControlUnit/done
add list /top_tb/TopUnit/ControlUnit/add
add list /top_tb/TopUnit/ControlUnit/and_s
add list /top_tb/TopUnit/ControlUnit/or_s
add list /top_tb/TopUnit/ControlUnit/xor_s
add list /top_tb/TopUnit/ControlUnit/sub
add list /top_tb/TopUnit/ControlUnit/jmp
add list /top_tb/TopUnit/ControlUnit/jc
add list /top_tb/TopUnit/ControlUnit/jnc
add list /top_tb/TopUnit/ControlUnit/Cflag
add list /top_tb/TopUnit/ControlUnit/Zflag
add list /top_tb/TopUnit/ControlUnit/Nflag
add list /top_tb/TopUnit/ControlUnit/IRin
add list /top_tb/TopUnit/ControlUnit/Imm1_in
add list /top_tb/TopUnit/ControlUnit/Imm2_in
add list /top_tb/TopUnit/ControlUnit/RFin
add list /top_tb/TopUnit/ControlUnit/RFout
add list /top_tb/TopUnit/ControlUnit/PCin
add list /top_tb/TopUnit/ControlUnit/Ain
add list /top_tb/TopUnit/ControlUnit/Cin
add list /top_tb/TopUnit/ControlUnit/Cout
add list /top_tb/TopUnit/ControlUnit/Mem_wr
add list /top_tb/TopUnit/ControlUnit/Mem_out
add list /top_tb/TopUnit/ControlUnit/Mem_in
add list /top_tb/TopUnit/ControlUnit/OPC
add list /top_tb/TopUnit/ControlUnit/PCsel
add list /top_tb/TopUnit/ControlUnit/RFaddr
add list /top_tb/TopUnit/ControlUnit/clk
add list /top_tb/TopUnit/ControlUnit/rst
add list /top_tb/TopUnit/ControlUnit/ena
add list /top_tb/TopUnit/ControlUnit/done_FSM
add list /top_tb/TopUnit/ControlUnit/prv_state
add list /top_tb/TopUnit/ControlUnit/nxt_state
add list /top_tb/TopUnit/ControlUnit/temp
add list /top_tb/TopUnit/DataPathUnit/st
add list /top_tb/TopUnit/DataPathUnit/ld
add list /top_tb/TopUnit/DataPathUnit/mov
add list /top_tb/TopUnit/DataPathUnit/done
add list /top_tb/TopUnit/DataPathUnit/add
add list /top_tb/TopUnit/DataPathUnit/sub
add list /top_tb/TopUnit/DataPathUnit/jmp
add list /top_tb/TopUnit/DataPathUnit/jc
add list /top_tb/TopUnit/DataPathUnit/jnc
add list /top_tb/TopUnit/DataPathUnit/xor_s
add list /top_tb/TopUnit/DataPathUnit/or_s
add list /top_tb/TopUnit/DataPathUnit/and_s
add list /top_tb/TopUnit/DataPathUnit/Cflag
add list /top_tb/TopUnit/DataPathUnit/Zflag
add list /top_tb/TopUnit/DataPathUnit/Nflag
add list /top_tb/TopUnit/DataPathUnit/IRin
add list /top_tb/TopUnit/DataPathUnit/Imm1_in
add list /top_tb/TopUnit/DataPathUnit/Imm2_in
add list /top_tb/TopUnit/DataPathUnit/RFin
add list /top_tb/TopUnit/DataPathUnit/RFout
add list /top_tb/TopUnit/DataPathUnit/PCin
add list /top_tb/TopUnit/DataPathUnit/Ain
add list /top_tb/TopUnit/DataPathUnit/Cin
add list /top_tb/TopUnit/DataPathUnit/Cout
add list /top_tb/TopUnit/DataPathUnit/Mem_wr
add list /top_tb/TopUnit/DataPathUnit/Mem_out
add list /top_tb/TopUnit/DataPathUnit/Mem_in
add list /top_tb/TopUnit/DataPathUnit/OPC
add list /top_tb/TopUnit/DataPathUnit/PCsel
add list /top_tb/TopUnit/DataPathUnit/RFaddr
add list /top_tb/TopUnit/DataPathUnit/TBactive
add list /top_tb/TopUnit/DataPathUnit/clk
add list /top_tb/TopUnit/DataPathUnit/rst
add list /top_tb/TopUnit/DataPathUnit/TBWriteEnableProgMem
add list /top_tb/TopUnit/DataPathUnit/TBWriteEnableDataMem
add list /top_tb/TopUnit/DataPathUnit/TBdataInProgMem
add list /top_tb/TopUnit/DataPathUnit/TBdataInDataMem
add list /top_tb/TopUnit/DataPathUnit/TBWriteAddressProgMem
add list /top_tb/TopUnit/DataPathUnit/TBWriteAddressDataMem
add list /top_tb/TopUnit/DataPathUnit/TBReadAddressDataMem
add list /top_tb/TopUnit/DataPathUnit/TBdataOutDataMem
add list /top_tb/TopUnit/DataPathUnit/dataOutProgMem
add list /top_tb/TopUnit/DataPathUnit/ReadAddressProgMem
add list /top_tb/TopUnit/DataPathUnit/dataOutDataMem
add list /top_tb/TopUnit/DataPathUnit/dataInDataMem
add list /top_tb/TopUnit/DataPathUnit/WriteAddressDataMem
add list /top_tb/TopUnit/DataPathUnit/ReadAddressDataMem
add list /top_tb/TopUnit/DataPathUnit/WriteAddressDataMemMuxOut
add list /top_tb/TopUnit/DataPathUnit/ReadAddressDataMemMuxOut
add list /top_tb/TopUnit/DataPathUnit/WriteEnableDataMem
add list /top_tb/TopUnit/DataPathUnit/WriteDataRF
add list /top_tb/TopUnit/DataPathUnit/ReadDataRF
add list /top_tb/TopUnit/DataPathUnit/ReadWriteAddressRF
add list /top_tb/TopUnit/DataPathUnit/A
add list /top_tb/TopUnit/DataPathUnit/B
add list /top_tb/TopUnit/DataPathUnit/C
add list /top_tb/TopUnit/DataPathUnit/CregisterOut
add list /top_tb/TopUnit/DataPathUnit/IR_OffsetAddress
add list /top_tb/TopUnit/DataPathUnit/IR_Immid
add list /top_tb/TopUnit/DataPathUnit/IROp
add list /top_tb/TopUnit/DataPathUnit/Immidiate
add list /top_tb/TopUnit/DataPathUnit/DataBUS
configure list -usestrobe 0
configure list -strobestart {0 ps} -strobeperiod {0 ps}
configure list -usesignaltrigger 1
configure list -delta collapse
configure list -signalnamewidth 0
configure list -datasetprefix 0
configure list -namelimit 5
