onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top_tb/done_FSM
add wave -noupdate /top_tb/rst
add wave -noupdate /top_tb/ena
add wave -noupdate /top_tb/clk
add wave -noupdate /top_tb/TBactive
add wave -noupdate /top_tb/TBWriteEnableDataMem
add wave -noupdate /top_tb/TBWriteEnableProgMem
add wave -noupdate /top_tb/TBdataInDataMem
add wave -noupdate /top_tb/TBdataOutDataMem
add wave -noupdate /top_tb/TBdataInProgMem
add wave -noupdate /top_tb/TBWriteAddressDataMem
add wave -noupdate /top_tb/TBWriteAddressProgMem
add wave -noupdate /top_tb/TBReadAddressDataMem
add wave -noupdate /top_tb/donePmemIn
add wave -noupdate /top_tb/doneDmemIn
add wave -noupdate /top_tb/TopUnit/ControlUnit/st
add wave -noupdate /top_tb/TopUnit/ControlUnit/ld
add wave -noupdate /top_tb/TopUnit/ControlUnit/mov
add wave -noupdate /top_tb/TopUnit/ControlUnit/done
add wave -noupdate /top_tb/TopUnit/ControlUnit/add
add wave -noupdate /top_tb/TopUnit/ControlUnit/and_s
add wave -noupdate /top_tb/TopUnit/ControlUnit/or_s
add wave -noupdate /top_tb/TopUnit/ControlUnit/xor_s
add wave -noupdate /top_tb/TopUnit/ControlUnit/sub
add wave -noupdate /top_tb/TopUnit/ControlUnit/jmp
add wave -noupdate /top_tb/TopUnit/ControlUnit/jc
add wave -noupdate /top_tb/TopUnit/ControlUnit/jnc
add wave -noupdate /top_tb/TopUnit/ControlUnit/Cflag
add wave -noupdate /top_tb/TopUnit/ControlUnit/Zflag
add wave -noupdate /top_tb/TopUnit/ControlUnit/Nflag
add wave -noupdate /top_tb/TopUnit/ControlUnit/IRin
add wave -noupdate /top_tb/TopUnit/ControlUnit/Imm1_in
add wave -noupdate /top_tb/TopUnit/ControlUnit/Imm2_in
add wave -noupdate /top_tb/TopUnit/ControlUnit/RFin
add wave -noupdate /top_tb/TopUnit/ControlUnit/RFout
add wave -noupdate /top_tb/TopUnit/ControlUnit/PCin
add wave -noupdate /top_tb/TopUnit/ControlUnit/Ain
add wave -noupdate /top_tb/TopUnit/ControlUnit/Cin
add wave -noupdate /top_tb/TopUnit/ControlUnit/Cout
add wave -noupdate /top_tb/TopUnit/ControlUnit/Mem_wr
add wave -noupdate /top_tb/TopUnit/ControlUnit/Mem_out
add wave -noupdate /top_tb/TopUnit/ControlUnit/Mem_in
add wave -noupdate /top_tb/TopUnit/ControlUnit/OPC
add wave -noupdate /top_tb/TopUnit/ControlUnit/PCsel
add wave -noupdate /top_tb/TopUnit/ControlUnit/RFaddr
add wave -noupdate /top_tb/TopUnit/ControlUnit/clk
add wave -noupdate /top_tb/TopUnit/ControlUnit/rst
add wave -noupdate /top_tb/TopUnit/ControlUnit/ena
add wave -noupdate /top_tb/TopUnit/ControlUnit/done_FSM
add wave -noupdate /top_tb/TopUnit/ControlUnit/prv_state
add wave -noupdate /top_tb/TopUnit/ControlUnit/nxt_state
add wave -noupdate /top_tb/TopUnit/ControlUnit/temp
add wave -noupdate /top_tb/TopUnit/DataPathUnit/st
add wave -noupdate /top_tb/TopUnit/DataPathUnit/ld
add wave -noupdate /top_tb/TopUnit/DataPathUnit/mov
add wave -noupdate /top_tb/TopUnit/DataPathUnit/done
add wave -noupdate /top_tb/TopUnit/DataPathUnit/add
add wave -noupdate /top_tb/TopUnit/DataPathUnit/sub
add wave -noupdate /top_tb/TopUnit/DataPathUnit/jmp
add wave -noupdate /top_tb/TopUnit/DataPathUnit/jc
add wave -noupdate /top_tb/TopUnit/DataPathUnit/jnc
add wave -noupdate /top_tb/TopUnit/DataPathUnit/xor_s
add wave -noupdate /top_tb/TopUnit/DataPathUnit/or_s
add wave -noupdate /top_tb/TopUnit/DataPathUnit/and_s
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Cflag
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Zflag
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Nflag
add wave -noupdate /top_tb/TopUnit/DataPathUnit/IRin
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Imm1_in
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Imm2_in
add wave -noupdate /top_tb/TopUnit/DataPathUnit/RFin
add wave -noupdate /top_tb/TopUnit/DataPathUnit/RFout
add wave -noupdate /top_tb/TopUnit/DataPathUnit/PCin
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Ain
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Cin
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Cout
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Mem_wr
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Mem_out
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Mem_in
add wave -noupdate /top_tb/TopUnit/DataPathUnit/OPC
add wave -noupdate /top_tb/TopUnit/DataPathUnit/PCsel
add wave -noupdate /top_tb/TopUnit/DataPathUnit/RFaddr
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBactive
add wave -noupdate /top_tb/TopUnit/DataPathUnit/clk
add wave -noupdate /top_tb/TopUnit/DataPathUnit/rst
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBWriteEnableProgMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBWriteEnableDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBdataInProgMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBdataInDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBWriteAddressProgMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBWriteAddressDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBReadAddressDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/TBdataOutDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/dataOutProgMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/ReadAddressProgMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/dataOutDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/dataInDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/WriteAddressDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/ReadAddressDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/WriteAddressDataMemMuxOut
add wave -noupdate /top_tb/TopUnit/DataPathUnit/ReadAddressDataMemMuxOut
add wave -noupdate /top_tb/TopUnit/DataPathUnit/WriteEnableDataMem
add wave -noupdate /top_tb/TopUnit/DataPathUnit/WriteDataRF
add wave -noupdate /top_tb/TopUnit/DataPathUnit/ReadDataRF
add wave -noupdate /top_tb/TopUnit/DataPathUnit/ReadWriteAddressRF
add wave -noupdate /top_tb/TopUnit/DataPathUnit/A
add wave -noupdate /top_tb/TopUnit/DataPathUnit/B
add wave -noupdate /top_tb/TopUnit/DataPathUnit/C
add wave -noupdate /top_tb/TopUnit/DataPathUnit/CregisterOut
add wave -noupdate /top_tb/TopUnit/DataPathUnit/IR_OffsetAddress
add wave -noupdate /top_tb/TopUnit/DataPathUnit/IR_Immid
add wave -noupdate /top_tb/TopUnit/DataPathUnit/IROp
add wave -noupdate /top_tb/TopUnit/DataPathUnit/Immidiate
add wave -noupdate /top_tb/TopUnit/DataPathUnit/DataBUS
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {142 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {2700 ps}
