-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MCU_tester IS
	GENERIC(IOSize : INTEGER := 8);
	PORT( 
		HEX0, HEX1			: IN	STD_LOGIC_VECTOR(6 DOWNTO 0);
		HEX2, HEX3			: IN	STD_LOGIC_VECTOR(6 DOWNTO 0);
		HEX4, HEX5			: IN	STD_LOGIC_VECTOR(6 DOWNTO 0);
		Switches			   : OUT	STD_LOGIC_VECTOR(7 DOWNTO 0);
      KEY1,KEY2,KEY3    : OUT   STD_LOGIC;
		clock       		: OUT   STD_LOGIC;
		ena					: OUT   STD_LOGIC;
		reset       : OUT   STD_LOGIC
   );

-- Declarations

END MCU_tester;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MCU_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic :='0';


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 25 ns;
         WAIT FOR 50 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 10000000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   ena	 <= '1';
   reset <= mw_U_1pulse;
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '1',
         '0' AFTER 20 ns,
         '1' AFTER 120 ns;
		-- '1' AFTER 2700 ns,
	--	 '0' AFTER 3500 ns;
      WAIT;
    END PROCESS u_1pulse_proc;

   -- Instance port mappings.
   Switches <= X"A5";

-- Key process for debugging without cpu   
  inter_key1_proc: PROCESS
  BEGIN
        KEY1 <= 
        '1',
        '0' AFTER 28000 ns,
        '1' AFTER 28100 ns;
       WAIT;
  END PROCESS inter_key1_proc;
   
   inter_key2_proc: PROCESS
   BEGIN
		KEY2 <= 
         '1',
         '0' AFTER 31000 ns,
         '1' AFTER 31100 ns;
        WAIT;
   END PROCESS inter_key2_proc;

   inter_key3_proc: PROCESS
   BEGIN
		KEY3 <= 
         '1',
         '0' AFTER 35000 ns,
         '1' AFTER 35100 ns;
        WAIT;
   END PROCESS inter_key3_proc;
   
 ---- Key process for debugging without cpu   
 -- inter_key1_proc: PROCESS
 -- BEGIN
 --       KEY1 <= 
 --       '1',
 --       '0' AFTER 3857 ns,
 --       '1' AFTER 4057 ns;
 --     WAIT;
 -- END PROCESS inter_key1_proc;

 -- Interrupt Ack prcoess debugging
--  inter_intA_proc: PROCESS
--  BEGIN
--        INTA <= 
--        '1',
--        '0' AFTER 7200 ns,
--        '1' AFTER 7400 ns;
--       WAIT;
--  END PROCESS inter_intA_proc; 
END struct;
